### PR TITLE
Fix posting to BGG

### PR DESCRIPTION
**Pull request by caitlin**
The new design broke the scripts that post to BGG.

This fixes those scripts.

### CODE REVIEW

**Comment by PilotBob** [comment]
Did you move the scripts from bin to werewolf/bgg? It looks like you copied them (unless I'm reading this diff wrong).

All the scripts in bin, expected all the scripts to be in bin. 

My preference would be to have all the scripts in one place. If that werewolf/bgg or bin I'm ok with that. As long as it all works. If possible I'd like to have everything be relative paths... or if we need an absolute path we add a env var for that.

**Comment by caitlin** [comment]
I moved them from `werewolf/php` to `werewolf/bgg`. I removed some of the duplicates from `bin` and repointing anything pointing to the ones in `bin` to mine. 

There are some related scripts still left in `bin` because they are related to auto mod. I haven't touched automod scripts yet.

We can put them in `bin`, I don't particularly care.. (though I'd prefer to group related scripts by folder).

Re: relative paths, I just copied the path that was already being used and moved it into a variable.

**Comment by caitlin** [comment]
Moved the scripts to bin. I'll address the relative path later.

**Comment by PilotBob** [comment]
Ok... I wasn't sure you changed everything in bin that was calling scripts to use your new ones. (locations aside).  But, I'll take your word for it.

In order to test this, can you create a branch in the CassandraWeb site for this (either PR into that branch or just copy your changes into it). This way, I can build the docker images and push them into a label so we can test them, before it all gets merged into master. (rather than merging into master directly).

I think I gave you maintainer status in this repo so you should be able to create branches and push to them.

**Comment by PilotBob** [comment]
Why the extra folder level (bgg)? Also, did you update paths in calls to those scripts? I only saw file move changes.

**Comment by caitlin** [comment]
I mean, that's why I like to test things to make sure I got everything. 😛

I don't find anything calling a `post_thread.pl`, except for `bin/save_automod.pl` calling `/opt/werewolf/post_thread.pl` a bunch. This needs cleanup. (It can probably simply use BGG class like the other calls, but I just haven't looked at it all yet.)
There's also `post_thread_pipe.pl` and `post_thread_cookie.pl` that I need to figure out what they are used for. 
All of those scripts are still going to be broken. (This is what I meant when I said automod was broken.)

**Comment by caitlin** [comment]
The extra folder to keep the purpose of scripts clear. 

The path is updated in `werewolf/php/bgg.php`.

**Comment by PilotBob** [comment]
collect_posts_fast.sh is what polls, builds the tally, etc. It uses post_thread_pipe.pl, 

https://github.com/CassandraWerewolf/CassandraWeb/blob/6d6dd11d667e7db9b3e367f3a62631315a242c2b/bin/collect_posts_fast.sh#L8

Start at run_collect_posts.sh and follow how that flows to poll that messages, and post the tallys.

**Comment by PilotBob** [comment]
>The extra folder to keep the purpose of scripts clear.

I mean, all the scripts are to interact with BGG. ;)

**Comment by caitlin** [comment]
> > The extra folder to keep the purpose of scripts clear.
> 
> I mean, all the scripts are to interact with BGG. ;)

Some interact directly with BGG API.
Some are related to the votes/tally and don't talk to BGG at all.
One is just a calendar related script. 

I'm just averse to flat file structures and am inclined to organize things in some fashion. I simply started with what I was working with (scripts related to bgg.php). We don't have to use the folder.

**Comment by caitlin** [comment]
> collect_posts_fast.sh is what polls, builds the tally, etc. It uses post_thread_pipe.pl,
> 
> https://github.com/CassandraWerewolf/CassandraWeb/blob/6d6dd11d667e7db9b3e367f3a62631315a242c2b/bin/collect_posts_fast.sh#L8
> 
> Start at run_collect_posts.sh and follow how that flows to poll that messages, and post the tallys.

Okay, looks like this will need addressing before this fix will work.

**Comment by PilotBob** [comment]
But all the scripts in the bin folder are what is used to do all the automation of poll, tally, post, send geekmail, etc. 

>I'm just averse to flat file structures and am inclined to organize things in some fashion. I simply started with what I was working with (scripts related to bgg.php). We don't have to use the folder.

Fair enough. I agree, but I also consider the number of items in a folder too.

**Comment by caitlin** [comment]
Alright, that should do it. 

From what I can tell, what is remaining is automod stuff. I'll tackle that tomorrow, but I think this can go out sooner so we can test.

**Comment by PilotBob** [comment]
Please create a PR from the branch in this repo.

**Pull request closed without merging**
